---
# Basics
baseURL: https://www.home-assistant.io
title: Home Assistant
googleAnalytics: UA-57927901-1

# We use YAML as our meta data format
metaDataFormat: yaml

# Blackfridy options (Hugo's Markdown rendering engine)
blackfriday:
  taskLists: true
  hrefTargetBlank: true
  nofollowLinks: true

# i18n
languageCode: en-US
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languages:
  en:
    weight: 1

# Default content dir, allows en to be in a subdir
contentDir: content/en

# Permalinks
permalinks:
  blog: /blog/:year/:month/:day/:slug/

# Some other settings
enableEmoji: true
enableGitInfo: true

# Menu
menu:

  # Main menu
  main:
    - name: Home
      identifier: menu.home
      url: /
      weight: 1
    - name: 'Option 1: Default Page'
      url: /
      weight: 1
      parent: menu.home
    - name: 'Option 2: Application'
      url: /
      weight: 2
      parent: menu.home
    - name: 'Option 3: Startup'
      url: /
      weight: 3
      parent: menu.home
    - name: 'Option 4: Agency'
      url: /
      weight: 4
      parent: menu.home
    - name: 'Option 5: Portfolio'
      url: /
      weight: 5
      parent: menu.home
    - name: Blog
      url: /blog/
      weight: 3
    - name: FAQ
      identifier: faq
      url: /faq/
      weight: 4
    - name: Contact
      url: /contact/
      weight: 5
    - name: Features
      identifier: menu.features
      url: /img/template-easy-customize.png
      weight: 3
    - name: Shortcodes
      identifier: section.shortcodes
      url: ''
      weight: 1
      parent: menu.features
      post: 1
    - name: Header variations
      identifier: section.headervariations
      url: ''
      weight: 2
      parent: menu.features
      post: 2
    - name: Accordionss
      url: ''
      weight: 1
      parent: section.shortcodes
    - name: Alerts
      url: ''
      weight: 2
      parent: section.shortcodes
    - name: Buttons
      url: ''
      weight: 3
      parent: section.shortcodes
    - name: Content Boxes
      url: ''
      weight: 4
      parent: section.shortcodes
    - name: Horizontal Blocks
      url: ''
      weight: 5
      parent: section.shortcodes
    - name: Pagination
      url: ''
      weight: 6
      parent: section.shortcodes
    - name: Tabs
      url: ''
      weight: 7
      parent: section.shortcodes
    - name: Typography
      url: ''
      weight: 8
      parent: section.shortcodes
    - name: Default Sticky Header
      url: ''
      weight: 1
      parent: section.headervariations
    - name: No Sticky Header
      url: ''
      weight: 2
      parent: section.headervariations
    - name: Light Header
      url: ''
      weight: 3
      parent: section.headervariations
    - name: Portfolio
      identifier: menu.portfolio
      url: /img/template-homepage.png
      weight: 3
    - name: Portfolio
      identifier: section.portfolio
      url: ''
      weight: 1
      parent: menu.portfolio
      post: 1
    - name: 2 Columns
      url: ''
      weight: 1
      parent: section.portfolio
    - name: 2 Columns With Negative Space
      url: ''
      weight: 2
      parent: section.portfolio
    - name: 3 Columns
      url: ''
      weight: 3
      parent: section.portfolio
    - name: 3 Columns With Negative Space
      url: ''
      weight: 4
      parent: section.portfolio
    - name: 4 Columns
      url: ''
      weight: 5
      parent: section.portfolio
    - name: 4 Columns With Negative Space
      url: ''
      weight: 6
      parent: section.portfolio
    - name: Portfolio - detail
      url: ''
      weight: 7
      parent: section.portfolio
    - name: Portfolio - detail 2
      url: ''
      weight: 8
      parent: section.portfolio
    - name: About
      identifier: section.about
      url: ''
      weight: 2
      parent: menu.portfolio
      post: 2
    - name: About Us
      url: ''
      weight: 1
      parent: section.about
    - name: Our Team
      url: ''
      weight: 2
      parent: section.about
    - name: Marketing
      identifier: section.marketing
      url: ''
      weight: 3
      parent: menu.portfolio
      post: 2
    - name: Packages
      url: ''
      weight: 1
      parent: section.marketing
    - name: All Pages
      identifier: menu.allpages
      url: ''
      weight: 4
    - name: Home
      identifier: section.ap-home
      url: ''
      weight: 1
      parent: menu.allpages
      post: 1
    - name: About
      identifier: section.ap-about
      url: ''
      weight: 2
      parent: menu.allpages
      post: 1
    - name: Marketing
      identifier: section.ap-marketing
      url: ''
      weight: 3
      parent: menu.allpages
      post: 1
    - name: Portfolio
      identifier: section.ap-portfolio
      url: ''
      weight: 1
      parent: menu.allpages
      post: 2
    - name: User Pages
      identifier: section.ap-userpages
      url: ''
      weight: 2
      parent: menu.allpages
      post: 2
    - name: Shop
      identifier: section.ap-shop
      url: ''
      weight: 1
      parent: menu.allpages
      post: 3
    - name: Shop - Order Process
      identifier: section.ap-shoporderprocess
      url: ''
      weight: 2
      parent: menu.allpages
      post: 3
    - name: Contact
      identifier: section.ap-contact
      url: ''
      weight: 1
      parent: menu.allpages
      post: 4
    - name: Pages
      identifier: section.ap-pages
      url: ''
      weight: 2
      parent: menu.allpages
      post: 4
    - name: Blog
      identifier: section.ap-blog
      url: ''
      weight: 3
      parent: menu.allpages
      post: 4
    - name: Blog Listing Big
      url: /blog/
      weight: 1
      parent: section.ap-blog
    - name: Contact
      url: /contact/
      weight: 6

  # Top bar menu
  topbar:
    - weight: 1
      name: GitHub
      url: 'https://github.com/devcows/hugo-universal-theme'
      pre: <i class='fa fa-2x fa-github'></i>
    - weight: 2
      name: Facebook
      url: 'http://facebook.com'
      pre: <i class='fa fa-2x fa-facebook'></i>
    - weight: 3
      name: Twitter
      url: 'http://twitter.com'
      pre: <i class='fa fa-2x fa-twitter'></i>
    - weight: 4
      name: Email
      url: 'mailto:your@email.com'
      pre: <i class='fa fa-2x fa-envelope'></i>


params:
  viewMorePostLink: /blog/
  author: DevCows
  defaultKeywords:
    - devows
    - hugo
    - go
  defaultDescription: Site template made by devcows using hugo
  googleMapsApiKey: AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y
  style: default
  email: your@email.com
  about_us: >-
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
    fames ac turpis egestas.</p>
  copyright: 'Copyright (c) 2015 - 2016, YourCompany; all rights reserved.'
  date_format: 'January 2, 2006'
  logo: img/logo.png
  address: |-
    <p><strong>Universal Ltd.</strong>
            <br>13/25 New Avenue
            <br>Newtown upon River
            <br>45Y 73J
            <br>England
            <br>
            <strong>Great Britain</strong>
          </p>

  latitude: '-12.043333'
  longitude: '-77.028333'
  topbar:
    enable: true
    text: >-
      <p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or
      hello@universal.com.</p>
            <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
            <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
            </p>

  widgets:
    categories: true
    tags: true
    search: true
  carousel:
    enable: true
  features:
    enable: true
  testimonials:
    enable: true
    title: Testimonials
    subtitle: >-
      We have worked with many clients and we always like to hear they come out
      from the cooperation happy and satisfied. Have a look what our clients
      said about us.
  see_more:
    enable: true
    icon: fa fa-file-code-o
    title: Do you want to see more?
    subtitle: >-
      We have prepared for you more than 40 different HTML pages, including 5
      variations of homepage.
    link_url: '#'
    link_text: Check other homepages
  clients:
    enable: true
    title: Our Clients
    subtitle: ''
  recent_posts:
    enable: true
    title: From our blog
    subtitle: >-
      Pellentesque habitant morbi tristique senectus et netus et malesuada fames
      ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
      tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
      Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
