name: CI

on: [push, pull_request]

jobs:
  markdown-lint:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - name: Checking out files from GitHub
        uses: actions/checkout@v2
      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Setting up NPM cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - name: Installing dependencies
        run: npm install
        env:
          CI: true
      - name: Running remark lint
        run: npm run markdown:lint
  build:
    name: Jekyll build
    runs-on: ubuntu-latest
    needs: [markdown-lint]
    steps:
      - name: Checking out files from GitHub
        uses: actions/checkout@v2
      - name: Setting up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setting up Ruby Gems cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gems-
      - name: Installing dependencies
        run: |
          gem install bundler -v 2.0.1
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Building site
        run: |
          bundle exec rake generate
  # deploy:
  #   name: Deploy website
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Deploying site
  #       uses: netlify/actions/cli@master
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #       with:
  #         args: deploy --dir=public --prod
  #         secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
